AdvancedOptions: true
DockerFilePath: Dockerfile
ServiceType: private
ArtifactSourceType: Dockerfile
ServiceBuildRegion: ap-southeast-1
RepoName: workhardliuzheng/quickstart-metabase
RegionId: cn-hangzhou
CustomParameters: ''
DockerBuildArgs:
- ArgumentValue: latest
  ArgumentName: VERSION
Owner: workhardliuzheng
Branch: master
Platform: github
